export const lang = {
  en: {
    // Onboarding
    tagline: 'Simple shop book',
    heroTitle: 'Know your sales, stock, profit, and people owing you.',
    heroBody: 'Ulahia helps a small shop owner record sales fast, know what remains in the shop, and see profit before closing.',
    start: 'Start selling',
    addGoods: 'Add goods',
    read: 'Read',
    private: 'Private on this device',
    trust: 'Built for small Android phones, poor network, and busy shops.',

    // Greetings
    greetMorning: 'Good morning',
    greetAfternoon: 'Good afternoon',
    greetEvening: 'Good evening',

    // Navigation labels
    dashboard: 'Home',
    sell: 'Sell',
    stock: 'Stock',
    navCustomers: 'Customers',
    navDebts: 'Debts',
    navProducts: 'Products',
    navReports: 'Reports',
    navSettings: 'Settings',

    // Home screen
    newSale: 'NEW SALE',
    customersSub: 'Search & manage',
    debtsSub: 'Who owes you',
    productsSub: 'Add & manage stock',
    reportsSub: 'Sales history',

    // Stats
    todaySales: 'Today sales',
    todayProfit: 'Today profit',
    stockLeft: 'Stock left',
    owing: 'Debt',

    // Time periods
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    allTime: 'All Time',

    // Reports
    sales: 'Sales',
    profit: 'Profit',
    total: 'Total',
    transactions: 'Transactions',
    noTransactions: 'No transactions in this period.',
    debtsOwed: 'Debts Owed',
    countedProducts: 'Counted Products',
    flexibleProducts: 'Flexible Products',
    invested: 'Invested',
    sold: 'Sold',
    recovery: 'Recovery',
    allCustomers: 'All customers',

    // Products
    product: 'Product',
    productName: 'Product Name',
    addProduct: 'Add Product',
    editProduct: 'Edit',
    deleteProduct: 'Delete',
    bulkRestock: 'Bulk Restock',
    noProductsYet: 'No products yet.',
    cost: 'Cost price',
    price: 'Selling price',
    qty: 'Quantity',
    units: 'units',
    lowStock: 'Low stock',
    outOfStock: 'Out',
    restock: 'Restock',
    addToStock: 'Add to Stock',
    currentStock: 'Current Stock',
    currentInvestment: 'Current Investment',
    newStockValue: 'New Stock Value (₦)',
    unitsReceived: 'Units Received',
    soldByAmount: 'Sold by amount — no cost entered',
    likelyOut: 'Likely Out',
    runningLow: 'Running Low',
    flexible: 'Flexible',
    stockLikelySoldOut: 'Stock likely sold out — tap Restock to add new inventory',

    // Checkout / Payment
    cash: 'Cash',
    transfer: 'Transfer',
    debt: 'Debt',
    checkout: 'Checkout',
    orderSummary: 'Order Summary',
    paymentMethod: 'Payment Method',
    amountReceived: 'Amount Received',
    received: 'Received',
    completeSale: 'Complete Sale',
    markAsPaid: 'Mark as Paid',
    recordDebt: 'Record Debt',
    changeReturn: 'Change to Return',
    partPayment: 'Part Payment Now',
    paidNow: 'Paid Now',
    willOwe: 'Will Owe',
    transferReceived: 'Transfer Received?',
    notConfirmed: 'Not Confirmed',
    confirmed: 'Confirmed',
    waitingConfirmation: 'Waiting for Confirmation…',
    transferNote: 'Check your phone or bank app to verify the transfer before completing.',
    transferReady: 'Transfer confirmed. Ready to complete sale.',

    // Customers / Debt
    customers: 'Debt',
    customerName: 'Customer name',
    phone: 'Phone number',
    amount: 'Amount',
    reason: 'What did they buy?',
    addDebt: 'Add debt',
    paid: 'Paid',
    noDebt: 'No debt recorded.',
    payAll: 'Pay Full',
    allDebts: 'Owing',
    clearedDebts: 'Cleared',
    recordPayment: 'Record Payment',
    amountPaid: 'Amount Paid',
    note: 'Note',
    confirmPayment: 'Confirm Payment',
    outstanding: 'outstanding',
    lastPaid: 'Last paid',
    noPhone: 'No phone',

    // Common actions
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    clear: 'Clear',
    optional: 'optional',

    // Settings
    shopDetails: 'Shop Details',
    shopName: 'Shop Name',
    yourName: 'Your Name',
    phoneNumber: 'Phone Number',
    saveChanges: 'Save Changes',
    demoReset: 'Demo & Reset',
    demoResetDesc: 'Load sample data to see how the app looks with real products and customers.',
    loadDemo: 'Load Demo Shop',
    exportData: 'Export Data',

    // Confirmations
    confirmDemoReset: 'This will replace all your data with demo data.',
    confirmClearCart: 'Remove all items from cart?',

    // Setup / onboarding
    shopReady: 'Mama Ngozi Store is ready',
    quickSale: 'Tap goods when customer buys',
    quickSaleHint: 'Stock goes down and profit shows by itself.',
    addFirstGoods: 'Add first goods',
    recordFirstSale: 'Record first sale',
    seeProfit: 'See your profit',

    // Misc
    offline: 'No internet. You can still use your last shop data.',
    reportText: 'This is the money story for today.',
  },

  pidgin: {
    // Onboarding
    tagline: 'Simple shop book',
    heroTitle: 'Know wetin you sell, wetin remain, profit, and who dey owe.',
    heroBody: 'Ulahia help shop owner record sales fast, know goods wey remain, and see profit before shop close.',
    start: 'Start to sell',
    addGoods: 'Add goods',
    read: 'Read',
    private: 'Private for this phone',
    trust: 'Built for small Android phones, weak network, and busy shops.',

    // Greetings
    greetMorning: 'Good morning',
    greetAfternoon: 'Good afternoon',
    greetEvening: 'Good evening',

    // Navigation labels
    dashboard: 'Home',
    sell: 'Sell',
    stock: 'Stock',
    navCustomers: 'Customers',
    navDebts: 'Debts',
    navProducts: 'Products',
    navReports: 'Reports',
    navSettings: 'Settings',

    // Home screen
    newSale: 'SELL NOW',
    customersSub: 'Search & manage',
    debtsSub: 'Who dey owe you',
    productsSub: 'Add & manage stock',
    reportsSub: 'Sales history',

    // Stats
    todaySales: 'Sales today',
    todayProfit: 'Profit today',
    stockLeft: 'Goods remain',
    owing: 'Debt',

    // Time periods
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    allTime: 'All Time',

    // Reports
    sales: 'Sales',
    profit: 'Profit',
    total: 'Total',
    transactions: 'Transactions',
    noTransactions: 'No sales dis time.',
    debtsOwed: 'People wey dey owe',
    countedProducts: 'Counted Goods',
    flexibleProducts: 'Flexible Goods',
    invested: 'Money put in',
    sold: 'Sold',
    recovery: 'Recovery',
    allCustomers: 'All customers',

    // Products
    product: 'Goods',
    productName: 'Goods Name',
    addProduct: 'Add Goods',
    editProduct: 'Edit',
    deleteProduct: 'Delete',
    bulkRestock: 'Bulk Restock',
    noProductsYet: 'No goods yet.',
    cost: 'Cost price',
    price: 'Selling price',
    qty: 'Quantity',
    units: 'units',
    lowStock: 'Goods dey finish',
    outOfStock: 'Finish',
    restock: 'Add more',
    addToStock: 'Add to Stock',
    currentStock: 'Current Stock',
    currentInvestment: 'Current Investment',
    newStockValue: 'New Stock Value (₦)',
    unitsReceived: 'Units Received',
    soldByAmount: 'Sold by amount — no cost entered',
    likelyOut: 'Likely Finish',
    runningLow: 'Almost Finish',
    flexible: 'Flexible',
    stockLikelySoldOut: 'Stock don finish — tap Restock to add more',

    // Checkout / Payment
    cash: 'Cash',
    transfer: 'Transfer',
    debt: 'Debt',
    checkout: 'Checkout',
    orderSummary: 'Order Summary',
    paymentMethod: 'How dem go pay',
    amountReceived: 'How much dem pay',
    received: 'Received',
    completeSale: 'Complete Sale',
    markAsPaid: 'Mark as Paid',
    recordDebt: 'Record Debt',
    changeReturn: 'Change to give',
    partPayment: 'Part Payment Now',
    paidNow: 'Paid now',
    willOwe: 'Go owe',
    transferReceived: 'Transfer Done?',
    notConfirmed: 'Not Confirmed',
    confirmed: 'Confirmed',
    waitingConfirmation: 'Waiting for Confirmation…',
    transferNote: 'Check your phone or bank app before you complete.',
    transferReady: 'Transfer confirmed. You fit complete now.',

    // Customers / Debt
    customers: 'Debt',
    customerName: 'Customer name',
    phone: 'Phone number',
    amount: 'Amount',
    reason: 'Wetin dem buy?',
    addDebt: 'Add debt',
    paid: 'Paid',
    noDebt: 'Nobody dey owe now.',
    payAll: 'Pay Full',
    allDebts: 'Who Dey Owe',
    clearedDebts: 'Don Pay',
    recordPayment: 'Record Payment',
    amountPaid: 'Amount Paid',
    note: 'Note',
    confirmPayment: 'Confirm Payment',
    outstanding: 'outstanding',
    lastPaid: 'Last paid',
    noPhone: 'No phone',

    // Common actions
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    clear: 'Clear',
    optional: 'optional',

    // Settings
    shopDetails: 'Shop Info',
    shopName: 'Shop name',
    yourName: 'Your name',
    phoneNumber: 'Phone number',
    saveChanges: 'Save changes',
    demoReset: 'Demo & Reset',
    demoResetDesc: 'Load sample data to see how the app go look with real products and customers.',
    loadDemo: 'Load Demo Shop',
    exportData: 'Export Data',

    // Confirmations
    confirmDemoReset: 'This go replace all your data with demo data.',
    confirmClearCart: 'Remove all items from cart?',

    // Setup / onboarding
    shopReady: 'Mama Ngozi Store don ready',
    quickSale: 'Tap goods when customer buy',
    quickSaleHint: 'Stock go reduce and profit go show by itself.',
    addFirstGoods: 'Add first goods',
    recordFirstSale: 'Record first sale',
    seeProfit: 'See your profit',

    // Misc
    offline: 'No internet. You still fit use your last shop data.',
    reportText: 'Na today money story be this.',
  },

  yo: {
    // Onboarding
    tagline: 'Iwe itaja to rorun',
    heroTitle: 'Mo tita, eru to ku, ere, ati awon to je gbese.',
    heroBody: 'Ulahia ran onitaja lowo lati ko tita sile, mo eru to ku, ki o si ri ere ojo naa.',
    start: 'Bẹrẹ tita',
    addGoods: 'Fi eru kun',
    read: 'Ka si mi',
    private: 'Ikoko lori ero yi',
    trust: 'A se fun Android kekere, network kekere, ati itaja to n sise.',

    // Greetings
    greetMorning: 'E kaaro',
    greetAfternoon: 'E kaasan',
    greetEvening: 'E kale',

    // Navigation labels
    dashboard: 'Ile',
    sell: 'Ta',
    stock: 'Eru',
    navCustomers: 'Alabara',
    navDebts: 'Gbese',
    navProducts: 'Eru',
    navReports: 'Iroyin',
    navSettings: 'Eto',

    // Home screen
    newSale: 'TITA TUNTUN',
    customersSub: 'Wa & sakoso',
    debtsSub: 'Tani o je gbese',
    productsSub: 'Fi eru kun & sakoso',
    reportsSub: 'Itan tita',

    // Stats
    todaySales: 'Tita oni',
    todayProfit: 'Ere oni',
    stockLeft: 'Eru to ku',
    owing: 'Gbese',

    // Time periods
    today: 'Oni',
    thisWeek: 'Ose yi',
    thisMonth: 'Osu yi',
    allTime: 'Gbogbo igba',

    // Reports
    sales: 'Tita',
    profit: 'Ere',
    total: 'Apapọ',
    transactions: 'Awon iṣowo',
    noTransactions: 'Ko si iṣowo fun akoko yi.',
    debtsOwed: 'Awon to n jẹ gbese',
    countedProducts: 'Awon eru ti a ka',
    flexibleProducts: 'Awon eru alafẹ',
    invested: 'Owo ti a lo',
    sold: 'Ta',
    recovery: 'Isọdọtun',
    allCustomers: 'Gbogbo alabara',

    // Products
    product: 'Eru',
    productName: 'Oruko eru',
    addProduct: 'Fi ẹru kun',
    editProduct: 'Se atunse',
    deleteProduct: 'Pa re',
    bulkRestock: 'Fi eru po kun',
    noProductsYet: 'Ko si ẹru.',
    cost: 'Owo rira',
    price: 'Owo tita',
    qty: 'Iye',
    units: 'iye',
    lowStock: 'Eru n pari',
    outOfStock: 'Parí',
    restock: 'Fi kun',
    addToStock: 'Fi eru kun',
    currentStock: 'Eru ti o wa',
    currentInvestment: 'Owo ti a lo tele',
    newStockValue: 'Iye tuntun (₦)',
    unitsReceived: 'Iye ti a gba',
    soldByAmount: 'A ta nipa owo — ko si iye',
    likelyOut: 'O le ti pari',
    runningLow: 'N dinku',
    flexible: 'Alafẹ',
    stockLikelySoldOut: 'Eru le ti tan — fi kun lati tun gba',

    // Checkout / Payment
    cash: 'Owo',
    transfer: 'Gbigbe',
    debt: 'Gbese',
    checkout: 'Isanwo',
    orderSummary: 'Akopọ paṣẹ',
    paymentMethod: 'Ọna isanwo',
    amountReceived: 'Owo ti a gba',
    received: 'Ti a gba',
    completeSale: 'Pari tita',
    markAsPaid: 'Fi ami si paid',
    recordDebt: 'Ko gbese sile',
    changeReturn: 'Iyipada',
    partPayment: 'Owo diẹ',
    paidNow: 'Asanwo',
    willOwe: 'Yio jẹ gbese',
    transferReceived: 'Gbigbe ti de?',
    notConfirmed: 'Ko ti daju',
    confirmed: 'Daju',
    waitingConfirmation: 'N duro idaniloju…',
    transferNote: 'Ṣayẹwo foonu tabi app banki re ki o pari.',
    transferReady: 'Gbigbe ti daju. O ti se lati pari.',

    // Customers / Debt
    customers: 'Gbese',
    customerName: 'Oruko alabara',
    phone: 'Nomba foonu',
    amount: 'Owo',
    reason: 'Kini won ra?',
    addDebt: 'Fi gbese kun',
    paid: 'Sanwo',
    noDebt: 'Ko si eni ti o je gbese.',
    payAll: 'San gbogbo',
    allDebts: 'Ti o je gbese',
    clearedDebts: 'Ti o sanwo',
    recordPayment: 'Ko isanwo sile',
    amountPaid: 'Owo ti a san',
    note: 'Akiyesi',
    confirmPayment: 'Daju isanwo',
    outstanding: 'to ku',
    lastPaid: 'Isanwo kẹhin',
    noPhone: 'Ko si foonu',

    // Common actions
    save: 'Fipamo',
    cancel: 'Pa de',
    search: 'Wa',
    clear: 'Pa rẹ',
    optional: 'aṣayan',

    // Settings
    shopDetails: 'Alaye shopo',
    shopName: 'Oruko shopo',
    yourName: 'Oruko re',
    phoneNumber: 'Nomba foonu',
    saveChanges: 'Fipamo ayipada',
    demoReset: 'Demo & Atunse',
    demoResetDesc: 'Gba data apẹẹrẹ lati wo bi app ṣe dabi pẹlu awọn ọja ati alabara gidi.',
    loadDemo: 'Gba shopo apẹẹrẹ',
    exportData: 'Mu data jade',

    // Confirmations
    confirmDemoReset: 'Eyi yoo paare gbogbo data re pelu data demo.',
    confirmClearCart: 'Paare gbogbo eru ninu cart?',

    // Setup / onboarding
    shopReady: 'Mama Ngozi Store ti setan',
    quickSale: 'Te eru ti alabara ra',
    quickSaleHint: 'Eru maa dinku, ere naa maa han.',
    addFirstGoods: 'Fi eru akoko kun',
    recordFirstSale: 'Ko tita akoko sile',
    seeProfit: 'Wo ere re',

    // Misc
    offline: 'Ko si internet. O tun le lo data itaja re.',
    reportText: 'Eyi ni itan owo oni.',
  },

  ig: {
    // Onboarding
    tagline: 'Akwukwo shop di mfe',
    heroTitle: 'Mara ihe rere, stock foduru, profit, na ndi ji ugwo.',
    heroBody: 'Ulahia na enyere onye shop aka ide sales ngwa ngwa, mata ihe foduru, hu profit kwa ubochi.',
    start: 'Malite ire',
    addGoods: 'Tinye ngwa',
    read: 'Gua',
    private: 'Nkeonwe na device a',
    trust: 'E wuru ya maka obere Android, network adighi ike, na shop na-eme ngwa.',

    // Greetings
    greetMorning: 'Ụtụtụ ọma',
    greetAfternoon: 'Ehihie ọma',
    greetEvening: 'Anyasị ọma',

    // Navigation labels
    dashboard: 'Home',
    sell: 'Ree',
    stock: 'Stock',
    navCustomers: 'Ndị Ahịa',
    navDebts: 'Ugwo',
    navProducts: 'Ngwa',
    navReports: 'Reports',
    navSettings: 'Ntọala',

    // Home screen
    newSale: 'ỌRERE ỌHỤRỤ',
    customersSub: 'Chọọ & njikwa',
    debtsSub: 'Onye ji ugwo',
    productsSub: 'Tinye & njikwa ngwa',
    reportsSub: 'Akụkọ sales',

    // Stats
    todaySales: 'Sales taa',
    todayProfit: 'Profit taa',
    stockLeft: 'Stock foduru',
    owing: 'Ndi ji ugwo',

    // Time periods
    today: 'Taa',
    thisWeek: 'Izu a',
    thisMonth: 'Onwa a',
    allTime: 'Oge niile',

    // Reports
    sales: 'Ire',
    profit: 'Uru',
    total: 'Nchịkọta',
    transactions: 'Azụmaahịa',
    noTransactions: 'Enweghị azụmaahịa n\'oge a.',
    debtsOwed: 'Ndị ji ugwo',
    countedProducts: 'Ngwa agụtara',
    flexibleProducts: 'Ngwa nwere nká',
    invested: 'Ego etinye',
    sold: 'Rere',
    recovery: 'Nwetaghachi',
    allCustomers: 'Ndị ahịa nile',

    // Products
    product: 'Ngwa',
    productName: 'Aha ngwa',
    addProduct: 'Tinye ngwa',
    editProduct: 'Dezie',
    deleteProduct: 'Hichapụ',
    bulkRestock: 'Tinye ngwa ọtụtụ',
    noProductsYet: 'Enweghị ngwa.',
    cost: 'Onu ahia izu',
    price: 'Onu ahia ire',
    qty: 'Ole',
    units: 'onu',
    lowStock: 'Stock na-agwu',
    outOfStock: 'Gwụọ',
    restock: 'Tinye ọzọ',
    addToStock: 'Tinye na stock',
    currentStock: 'Stock ugbu a',
    currentInvestment: 'Ego etinye ugbu a',
    newStockValue: 'Ego ọhụrụ (₦)',
    unitsReceived: 'Onu natara',
    soldByAmount: 'A na-ere site n\'ego — enweghị onu',
    likelyOut: 'Nwere ike gwụọ',
    runningLow: 'Na-agwu',
    flexible: 'Nwere nká',
    stockLikelySoldOut: 'Stock nwere ike gwụọ — tinye ọzọ',

    // Checkout / Payment
    cash: 'Ego',
    transfer: 'Nyefee',
    debt: 'Ugwo',
    checkout: 'Kwuo ọnụ',
    orderSummary: 'Nchịkọta ọrịa',
    paymentMethod: 'Ụzọ ikwu ọnụ',
    amountReceived: 'Ego natara',
    received: 'Natara',
    completeSale: 'Mechaa ire',
    markAsPaid: 'Dee na paid',
    recordDebt: 'Dee ugwo',
    changeReturn: 'Mgbanwe',
    partPayment: 'Ego ọfụụ ugbu a',
    paidNow: 'Kwuọla ugbu a',
    willOwe: 'Ga-anọ na ugwo',
    transferReceived: 'Nyefeela ego?',
    notConfirmed: 'Adighi ama',
    confirmed: 'Amatara',
    waitingConfirmation: 'Na-atụ aro…',
    transferNote: 'Lelee ekwentị ma ọ bụ app ụlọ akụ gị tupu ị mechaa.',
    transferReady: 'Nyefe amatara. I dị njikere mechaa.',

    // Customers / Debt
    customers: 'Ugwo',
    customerName: 'Aha customer',
    phone: 'Nomba phone',
    amount: 'Ego',
    reason: 'Gini ka ha zuru?',
    addDebt: 'Tinye ugwo',
    paid: 'Akwugo',
    noDebt: 'Onweghị onye ji ugwo ugbu a.',
    payAll: 'Kwuo nile',
    allDebts: 'Ji ugwo',
    clearedDebts: 'Kwuola',
    recordPayment: 'Dee ikwu ọnụ',
    amountPaid: 'Ego kwuọ',
    note: 'Ihe ọ bụla',
    confirmPayment: 'Kwado ikwu ọnụ',
    outstanding: 'fọdụrụ',
    lastPaid: 'Ikwu ikpeazụ',
    noPhone: 'Enweghị ekwentị',

    // Common actions
    save: 'Chekwaa',
    cancel: 'Kagbuo',
    search: 'Chọọ',
    clear: 'Hichaa',
    optional: 'ọ dịghị mkpa',

    // Settings
    shopDetails: 'Ozi shọp',
    shopName: 'Aha shọp',
    yourName: 'Aha gị',
    phoneNumber: 'Nomba phone',
    saveChanges: 'Chekwaa mgbanwe',
    demoReset: 'Demo & Ntọghachi',
    demoResetDesc: 'Tinye data ọmụmaatụ ịhụ otu app a dị na ngwa na ndị ahịa.',
    loadDemo: 'Tinye ọmụmaatụ shọp',
    exportData: 'Bupụ data',

    // Confirmations
    confirmDemoReset: 'Nke a ga-anọchi anya data nke gị na data demo.',
    confirmClearCart: 'Hichapụ ihe nile na cart?',

    // Setup / onboarding
    shopReady: 'Mama Ngozi Store di njikere',
    quickSale: 'Pia ngwa mgbe customer zuru',
    quickSaleHint: 'Stock ga-ebelata, profit ga-aputa.',
    addFirstGoods: 'Tinye ngwa mbu',
    recordFirstSale: 'Dee sale mbu',
    seeProfit: 'Hu profit gi',

    // Misc
    offline: 'Internet adighi. I ka nwere ike iji data shop gi.',
    reportText: 'Nke a bu akụkọ ego taa.',
  },

  ha: {
    // Onboarding
    tagline: 'Littafin shago mai sauki',
    heroTitle: 'San sayarwa, kaya da suka rage, riba, da masu bashi.',
    heroBody: 'Ulahia na taimaka wa mai shago rubuta sayarwa da sauri, ganin kaya da suka rage, da ribar yau.',
    start: 'Fara sayarwa',
    addGoods: 'Kara kaya',
    read: 'Karanta',
    private: 'Na sirri a wannan waya',
    trust: 'An gina shi domin kananan Android, network mara karfi, da shaguna masu aiki.',

    // Greetings
    greetMorning: 'Barka da safiya',
    greetAfternoon: 'Barka da rana',
    greetEvening: 'Barka da yamma',

    // Navigation labels
    dashboard: 'Gida',
    sell: 'Sayar',
    stock: 'Kaya',
    navCustomers: 'Abokan ciniki',
    navDebts: 'Bashi',
    navProducts: 'Kaya',
    navReports: 'Rahoto',
    navSettings: 'Saiti',

    // Home screen
    newSale: 'SABON SAYARWA',
    customersSub: 'Nema & sarrafa',
    debtsSub: 'Wanda ke da bashi',
    productsSub: 'Kara & sarrafa kaya',
    reportsSub: 'Tarihin sayarwa',

    // Stats
    todaySales: 'Sayarwa yau',
    todayProfit: 'Riba yau',
    stockLeft: 'Kaya sun rage',
    owing: 'Bashi',

    // Time periods
    today: 'Yau',
    thisWeek: 'Wannan mako',
    thisMonth: 'Wannan wata',
    allTime: 'Duk lokaci',

    // Reports
    sales: 'Sayarwa',
    profit: 'Riba',
    total: 'Jimla',
    transactions: 'Ma\'amaloli',
    noTransactions: 'Babu ma\'amaloli a wannan lokaci.',
    debtsOwed: 'Masu bashi',
    countedProducts: 'Kayan da aka kirga',
    flexibleProducts: 'Kayan sassauci',
    invested: 'Jari',
    sold: 'Sayarwa',
    recovery: 'Dawo',
    allCustomers: 'Duk abokan ciniki',

    // Products
    product: 'Kaya',
    productName: 'Sunan kaya',
    addProduct: 'Kara kaya',
    editProduct: 'Gyara',
    deleteProduct: 'Share',
    bulkRestock: 'Kara kaya da yawa',
    noProductsYet: 'Babu kaya.',
    cost: 'Farashin siya',
    price: 'Farashin sayarwa',
    qty: 'Adadi',
    units: 'adadi',
    lowStock: 'Kaya na karewa',
    outOfStock: 'Karewa',
    restock: 'Kara kaya',
    addToStock: 'Kara zuwa kaya',
    currentStock: 'Kaya yanzu',
    currentInvestment: 'Jari yanzu',
    newStockValue: 'Kudin sabon kaya (₦)',
    unitsReceived: 'Adadin da aka karba',
    soldByAmount: 'Ana saye da kudi — babu adadi',
    likelyOut: 'Watakila ya kare',
    runningLow: 'Na karewa',
    flexible: 'Mai sassauci',
    stockLikelySoldOut: 'Kaya na iya karewa — kara kaya',

    // Checkout / Payment
    cash: 'Kudi',
    transfer: 'Canja',
    debt: 'Bashi',
    checkout: 'Biya',
    orderSummary: 'Takaitaccen umarni',
    paymentMethod: 'Hanyar biya',
    amountReceived: 'Adadin da aka karba',
    received: 'An karba',
    completeSale: 'Kammala sayarwa',
    markAsPaid: 'Alama an biya',
    recordDebt: 'Rubuta bashi',
    changeReturn: 'Canji',
    partPayment: 'Biyan gefe yanzu',
    paidNow: 'An biya yanzu',
    willOwe: 'Zai bashi',
    transferReceived: 'An canja kudin?',
    notConfirmed: 'Ba a tabbata ba',
    confirmed: 'An tabbata',
    waitingConfirmation: 'Ana jiran tabbaci…',
    transferNote: 'Duba wayarka ko app banki kafin ka kammala.',
    transferReady: 'Canja an tabbata. Kana iya kammala.',

    // Customers / Debt
    customers: 'Bashi',
    customerName: 'Sunan customer',
    phone: 'Lambar waya',
    amount: 'Kudi',
    reason: 'Me suka saya?',
    addDebt: 'Kara bashi',
    paid: 'An biya',
    noDebt: 'Babu wanda ke da bashi yanzu.',
    payAll: 'Biya duka',
    allDebts: 'Masu bashi',
    clearedDebts: 'Sun biya',
    recordPayment: 'Rubuta biya',
    amountPaid: 'Adadin da aka biya',
    note: 'Bayani',
    confirmPayment: 'Tabbatar biya',
    outstanding: 'ya rage',
    lastPaid: 'Biyan karshe',
    noPhone: 'Babu waya',

    // Common actions
    save: 'Ajiye',
    cancel: 'Soke',
    search: 'Nema',
    clear: 'Share',
    optional: 'zaɓi',

    // Settings
    shopDetails: 'Bayanan shago',
    shopName: 'Sunan shago',
    yourName: 'Sunanka',
    phoneNumber: 'Lambar waya',
    saveChanges: 'Ajiye canje',
    demoReset: 'Demo & Sake daidaitawa',
    demoResetDesc: 'Loda bayanan misali don ganin yadda app ke kama da kayan aiki da abokan ciniki na gaske.',
    loadDemo: 'Shigo Demo Shago',
    exportData: 'Fitar data',

    // Confirmations
    confirmDemoReset: 'Wannan zai maye duk bayananku da bayanin demo.',
    confirmClearCart: 'Share duk abubuwan cikin cart?',

    // Setup / onboarding
    shopReady: 'Mama Ngozi Store ta shirya',
    quickSale: 'Danna kaya idan customer ya saya',
    quickSaleHint: 'Kaya zai ragu, riba zata bayyana.',
    addFirstGoods: 'Kara kaya na farko',
    recordFirstSale: 'Rubuta sayarwa ta farko',
    seeProfit: 'Ga ribarka',

    // Misc
    offline: 'Babu internet. Zaka iya amfani da bayanan shagoka.',
    reportText: 'Wannan shine labarin kudin yau.',
  },
}
